# Generated by Django 5.2.1 on 2025-06-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=150)),
                ('numero_registration', models.CharField(max_length=100, unique=True)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('año', models.PositiveSmallIntegerField()),
                ('estado', models.TextField()),
            ],
        ),
    ]
